// Code generated by protoc-gen-go. DO NOT EDIT.
// source: records/recordspb/records.proto

package recordspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Records struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Carrier              string   `protobuf:"bytes,3,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Score                string   `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Records) Reset()         { *m = Records{} }
func (m *Records) String() string { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()    {}
func (*Records) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{0}
}

func (m *Records) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Records.Unmarshal(m, b)
}
func (m *Records) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Records.Marshal(b, m, deterministic)
}
func (m *Records) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Records.Merge(m, src)
}
func (m *Records) XXX_Size() int {
	return xxx_messageInfo_Records.Size(m)
}
func (m *Records) XXX_DiscardUnknown() {
	xxx_messageInfo_Records.DiscardUnknown(m)
}

var xxx_messageInfo_Records proto.InternalMessageInfo

func (m *Records) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Records) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Records) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *Records) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

type CreateRecordsRequest struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordsRequest) Reset()         { *m = CreateRecordsRequest{} }
func (m *CreateRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordsRequest) ProtoMessage()    {}
func (*CreateRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{1}
}

func (m *CreateRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordsRequest.Unmarshal(m, b)
}
func (m *CreateRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordsRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordsRequest.Merge(m, src)
}
func (m *CreateRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordsRequest.Size(m)
}
func (m *CreateRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordsRequest proto.InternalMessageInfo

func (m *CreateRecordsRequest) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

type CreateRecordsResponse struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordsResponse) Reset()         { *m = CreateRecordsResponse{} }
func (m *CreateRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRecordsResponse) ProtoMessage()    {}
func (*CreateRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{2}
}

func (m *CreateRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordsResponse.Unmarshal(m, b)
}
func (m *CreateRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordsResponse.Marshal(b, m, deterministic)
}
func (m *CreateRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordsResponse.Merge(m, src)
}
func (m *CreateRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRecordsResponse.Size(m)
}
func (m *CreateRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordsResponse proto.InternalMessageInfo

func (m *CreateRecordsResponse) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

type ReadRecordsRequest struct {
	RecordsId            string   `protobuf:"bytes,1,opt,name=records_id,json=recordsId,proto3" json:"records_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRecordsRequest) Reset()         { *m = ReadRecordsRequest{} }
func (m *ReadRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRecordsRequest) ProtoMessage()    {}
func (*ReadRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{3}
}

func (m *ReadRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRecordsRequest.Unmarshal(m, b)
}
func (m *ReadRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ReadRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRecordsRequest.Merge(m, src)
}
func (m *ReadRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRecordsRequest.Size(m)
}
func (m *ReadRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRecordsRequest proto.InternalMessageInfo

func (m *ReadRecordsRequest) GetRecordsId() string {
	if m != nil {
		return m.RecordsId
	}
	return ""
}

type ReadRecordsResponse struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRecordsResponse) Reset()         { *m = ReadRecordsResponse{} }
func (m *ReadRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadRecordsResponse) ProtoMessage()    {}
func (*ReadRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{4}
}

func (m *ReadRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRecordsResponse.Unmarshal(m, b)
}
func (m *ReadRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRecordsResponse.Marshal(b, m, deterministic)
}
func (m *ReadRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRecordsResponse.Merge(m, src)
}
func (m *ReadRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadRecordsResponse.Size(m)
}
func (m *ReadRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRecordsResponse proto.InternalMessageInfo

func (m *ReadRecordsResponse) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

type UpdateRecordsRequest struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordsRequest) Reset()         { *m = UpdateRecordsRequest{} }
func (m *UpdateRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordsRequest) ProtoMessage()    {}
func (*UpdateRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{5}
}

func (m *UpdateRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordsRequest.Unmarshal(m, b)
}
func (m *UpdateRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordsRequest.Merge(m, src)
}
func (m *UpdateRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordsRequest.Size(m)
}
func (m *UpdateRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordsRequest proto.InternalMessageInfo

func (m *UpdateRecordsRequest) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

type UpdateRecordsResponse struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordsResponse) Reset()         { *m = UpdateRecordsResponse{} }
func (m *UpdateRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordsResponse) ProtoMessage()    {}
func (*UpdateRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{6}
}

func (m *UpdateRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordsResponse.Unmarshal(m, b)
}
func (m *UpdateRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordsResponse.Merge(m, src)
}
func (m *UpdateRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordsResponse.Size(m)
}
func (m *UpdateRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordsResponse proto.InternalMessageInfo

func (m *UpdateRecordsResponse) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

type DeleteRecordsRequest struct {
	RecordsId            string   `protobuf:"bytes,1,opt,name=records_id,json=recordsId,proto3" json:"records_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordsRequest) Reset()         { *m = DeleteRecordsRequest{} }
func (m *DeleteRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordsRequest) ProtoMessage()    {}
func (*DeleteRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{7}
}

func (m *DeleteRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordsRequest.Unmarshal(m, b)
}
func (m *DeleteRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordsRequest.Merge(m, src)
}
func (m *DeleteRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordsRequest.Size(m)
}
func (m *DeleteRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordsRequest proto.InternalMessageInfo

func (m *DeleteRecordsRequest) GetRecordsId() string {
	if m != nil {
		return m.RecordsId
	}
	return ""
}

type DeleteRecordsResponse struct {
	RecordsId            string   `protobuf:"bytes,1,opt,name=records_id,json=recordsId,proto3" json:"records_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordsResponse) Reset()         { *m = DeleteRecordsResponse{} }
func (m *DeleteRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordsResponse) ProtoMessage()    {}
func (*DeleteRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{8}
}

func (m *DeleteRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordsResponse.Unmarshal(m, b)
}
func (m *DeleteRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordsResponse.Merge(m, src)
}
func (m *DeleteRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordsResponse.Size(m)
}
func (m *DeleteRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordsResponse proto.InternalMessageInfo

func (m *DeleteRecordsResponse) GetRecordsId() string {
	if m != nil {
		return m.RecordsId
	}
	return ""
}

type ListRecordsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{9}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

type ListRecordsResponse struct {
	Records              *Records `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsResponse) Reset()         { *m = ListRecordsResponse{} }
func (m *ListRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecordsResponse) ProtoMessage()    {}
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5cc77764bf3a08, []int{10}
}

func (m *ListRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsResponse.Unmarshal(m, b)
}
func (m *ListRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsResponse.Marshal(b, m, deterministic)
}
func (m *ListRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsResponse.Merge(m, src)
}
func (m *ListRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecordsResponse.Size(m)
}
func (m *ListRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsResponse proto.InternalMessageInfo

func (m *ListRecordsResponse) GetRecords() *Records {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Records)(nil), "records.Records")
	proto.RegisterType((*CreateRecordsRequest)(nil), "records.CreateRecordsRequest")
	proto.RegisterType((*CreateRecordsResponse)(nil), "records.CreateRecordsResponse")
	proto.RegisterType((*ReadRecordsRequest)(nil), "records.ReadRecordsRequest")
	proto.RegisterType((*ReadRecordsResponse)(nil), "records.ReadRecordsResponse")
	proto.RegisterType((*UpdateRecordsRequest)(nil), "records.UpdateRecordsRequest")
	proto.RegisterType((*UpdateRecordsResponse)(nil), "records.UpdateRecordsResponse")
	proto.RegisterType((*DeleteRecordsRequest)(nil), "records.DeleteRecordsRequest")
	proto.RegisterType((*DeleteRecordsResponse)(nil), "records.DeleteRecordsResponse")
	proto.RegisterType((*ListRecordsRequest)(nil), "records.ListRecordsRequest")
	proto.RegisterType((*ListRecordsResponse)(nil), "records.ListRecordsResponse")
}

func init() { proto.RegisterFile("records/recordspb/records.proto", fileDescriptor_1a5cc77764bf3a08) }

var fileDescriptor_1a5cc77764bf3a08 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0x66, 0x9b, 0x5a, 0x7a, 0xa5, 0x43, 0x62, 0x07, 0x65, 0x3a, 0x95, 0x3e, 0x89, 0x0f, 0x53,
	0x36, 0xf4, 0xdd, 0xce, 0x07, 0x15, 0xe9, 0x43, 0xc5, 0x17, 0x5f, 0x46, 0xd7, 0x1c, 0x58, 0x90,
	0xa5, 0x26, 0xd5, 0x9f, 0xe2, 0xef, 0x95, 0xb5, 0x69, 0x49, 0xba, 0xc8, 0xd8, 0x7c, 0x4a, 0xee,
	0x72, 0xf7, 0xdd, 0x77, 0xf7, 0x1d, 0x81, 0x33, 0x8e, 0x29, 0xe3, 0x54, 0x5c, 0xc9, 0x33, 0x5f,
	0xd4, 0xb7, 0x71, 0xce, 0x59, 0xc1, 0x88, 0x25, 0xcd, 0x60, 0x0e, 0x56, 0x5c, 0x5d, 0x49, 0x1f,
	0xba, 0x19, 0xf5, 0x3b, 0xe7, 0x9d, 0x0b, 0x3b, 0xee, 0x66, 0x94, 0x78, 0xb0, 0x9f, 0xbf, 0xb3,
	0x25, 0xfa, 0xdd, 0xd2, 0x55, 0x19, 0xc4, 0x07, 0x2b, 0x4d, 0x38, 0xcf, 0x90, 0xfb, 0xbd, 0xd2,
	0x5f, 0x9b, 0xab, 0x78, 0x91, 0x32, 0x8e, 0xfe, 0x5e, 0x15, 0x5f, 0x1a, 0x41, 0x08, 0xde, 0x8c,
	0x63, 0x52, 0xa0, 0x2c, 0x13, 0xe3, 0xe7, 0x17, 0x8a, 0x82, 0x5c, 0x42, 0xcd, 0xa1, 0x2c, 0xe9,
	0x4c, 0x0e, 0xc7, 0x35, 0xc5, 0x3a, 0xb2, 0x21, 0x39, 0x83, 0x41, 0x0b, 0x43, 0xe4, 0x6c, 0x29,
	0x70, 0x2b, 0x90, 0x29, 0x90, 0x18, 0x13, 0xda, 0xa2, 0x31, 0x02, 0x90, 0x01, 0xf3, 0xa6, 0x79,
	0x5b, 0x7a, 0x1e, 0x69, 0x70, 0x07, 0x47, 0x5a, 0xd2, 0x0e, 0x75, 0x43, 0xf0, 0x5e, 0x73, 0xfa,
	0xef, 0x01, 0xb4, 0x30, 0x76, 0x20, 0x72, 0x03, 0xde, 0x3d, 0x7e, 0xe0, 0x1a, 0x91, 0x0d, 0x23,
	0xb8, 0x85, 0x41, 0x2b, 0x4d, 0xd6, 0xde, 0x90, 0xe7, 0x01, 0x79, 0xce, 0x44, 0xa1, 0x17, 0x5b,
	0x0d, 0x54, 0xf3, 0x6e, 0xdf, 0xc7, 0xe4, 0xa7, 0x07, 0x7d, 0xe9, 0x7c, 0x41, 0xfe, 0x9d, 0xa5,
	0x48, 0x22, 0x70, 0xb5, 0x05, 0x21, 0xa3, 0x26, 0xdd, 0xb4, 0x7c, 0xc3, 0xd3, 0xbf, 0x9e, 0x25,
	0x9d, 0x07, 0x70, 0x14, 0xd9, 0xc9, 0xb1, 0x42, 0xa6, 0xbd, 0x41, 0xc3, 0x13, 0xf3, 0xa3, 0x44,
	0x8a, 0xc0, 0xd5, 0x94, 0x53, 0x98, 0x99, 0xb6, 0x42, 0x61, 0x66, 0x16, 0x3c, 0x02, 0x57, 0x53,
	0x43, 0xc1, 0x33, 0x89, 0xab, 0xe0, 0x99, 0x45, 0x7c, 0x02, 0x47, 0xd1, 0x43, 0xe9, 0x74, 0x5d,
	0x3b, 0xa5, 0x53, 0x83, 0x84, 0xd7, 0x9d, 0xd0, 0x79, 0xb3, 0x9b, 0xff, 0x66, 0x71, 0x50, 0x7e,
	0x34, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xbd, 0x28, 0xcb, 0x8b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordsServiceClient is the client API for RecordsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordsServiceClient interface {
	CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*CreateRecordsResponse, error)
	ReadRecords(ctx context.Context, in *ReadRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error)
	UpdateRecords(ctx context.Context, in *UpdateRecordsRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error)
	DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsResponse, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (RecordsService_ListRecordsClient, error)
}

type recordsServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecordsServiceClient(cc *grpc.ClientConn) RecordsServiceClient {
	return &recordsServiceClient{cc}
}

func (c *recordsServiceClient) CreateRecords(ctx context.Context, in *CreateRecordsRequest, opts ...grpc.CallOption) (*CreateRecordsResponse, error) {
	out := new(CreateRecordsResponse)
	err := c.cc.Invoke(ctx, "/records.RecordsService/CreateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsServiceClient) ReadRecords(ctx context.Context, in *ReadRecordsRequest, opts ...grpc.CallOption) (*ReadRecordsResponse, error) {
	out := new(ReadRecordsResponse)
	err := c.cc.Invoke(ctx, "/records.RecordsService/ReadRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsServiceClient) UpdateRecords(ctx context.Context, in *UpdateRecordsRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error) {
	out := new(UpdateRecordsResponse)
	err := c.cc.Invoke(ctx, "/records.RecordsService/UpdateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsServiceClient) DeleteRecords(ctx context.Context, in *DeleteRecordsRequest, opts ...grpc.CallOption) (*DeleteRecordsResponse, error) {
	out := new(DeleteRecordsResponse)
	err := c.cc.Invoke(ctx, "/records.RecordsService/DeleteRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (RecordsService_ListRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RecordsService_serviceDesc.Streams[0], "/records.RecordsService/ListRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordsServiceListRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecordsService_ListRecordsClient interface {
	Recv() (*ListRecordsResponse, error)
	grpc.ClientStream
}

type recordsServiceListRecordsClient struct {
	grpc.ClientStream
}

func (x *recordsServiceListRecordsClient) Recv() (*ListRecordsResponse, error) {
	m := new(ListRecordsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecordsServiceServer is the server API for RecordsService service.
type RecordsServiceServer interface {
	CreateRecords(context.Context, *CreateRecordsRequest) (*CreateRecordsResponse, error)
	ReadRecords(context.Context, *ReadRecordsRequest) (*ReadRecordsResponse, error)
	UpdateRecords(context.Context, *UpdateRecordsRequest) (*UpdateRecordsResponse, error)
	DeleteRecords(context.Context, *DeleteRecordsRequest) (*DeleteRecordsResponse, error)
	ListRecords(*ListRecordsRequest, RecordsService_ListRecordsServer) error
}

func RegisterRecordsServiceServer(s *grpc.Server, srv RecordsServiceServer) {
	s.RegisterService(&_RecordsService_serviceDesc, srv)
}

func _RecordsService_CreateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServiceServer).CreateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/records.RecordsService/CreateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServiceServer).CreateRecords(ctx, req.(*CreateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordsService_ReadRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServiceServer).ReadRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/records.RecordsService/ReadRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServiceServer).ReadRecords(ctx, req.(*ReadRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordsService_UpdateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServiceServer).UpdateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/records.RecordsService/UpdateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServiceServer).UpdateRecords(ctx, req.(*UpdateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordsService_DeleteRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServiceServer).DeleteRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/records.RecordsService/DeleteRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServiceServer).DeleteRecords(ctx, req.(*DeleteRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordsService_ListRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordsServiceServer).ListRecords(m, &recordsServiceListRecordsServer{stream})
}

type RecordsService_ListRecordsServer interface {
	Send(*ListRecordsResponse) error
	grpc.ServerStream
}

type recordsServiceListRecordsServer struct {
	grpc.ServerStream
}

func (x *recordsServiceListRecordsServer) Send(m *ListRecordsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RecordsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "records.RecordsService",
	HandlerType: (*RecordsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecords",
			Handler:    _RecordsService_CreateRecords_Handler,
		},
		{
			MethodName: "ReadRecords",
			Handler:    _RecordsService_ReadRecords_Handler,
		},
		{
			MethodName: "UpdateRecords",
			Handler:    _RecordsService_UpdateRecords_Handler,
		},
		{
			MethodName: "DeleteRecords",
			Handler:    _RecordsService_DeleteRecords_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRecords",
			Handler:       _RecordsService_ListRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "records/recordspb/records.proto",
}
